
services:
  ### DATABASE: SQL SERVER ###
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver_container
    restart: always
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "Password789"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./init-scripts:/docker-entrypoint-initdb.d

    entrypoint: [ "/bin/bash", "-c", "/docker-entrypoint-initdb.d/init-db.sh & exec /opt/mssql/bin/sqlservr" ]

    healthcheck:
      test: [ "CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "SA", "-P", "Password789", "-Q", "SELECT name FROM sys.databases WHERE name = 'pis'", "-N", "o" ]
      interval: 10s
      timeout: 10s
      retries: 5

    networks:
      - springboot-network

  ### BACKEND: SPRING BOOT ###
  springboot:
    build: .
    container_name: springboot_container
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://sqlserver:1433;databaseName=pis;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: SA
      SPRING_DATASOURCE_PASSWORD: Password789
    depends_on:
      sqlserver:
        condition: service_healthy

    networks:
      - springboot-network

networks:
  springboot-network:

volumes:
  mssql_data: