server:
  port: 443
  ssl:
    enabled: true
    key-store: file:/etc/ssl/keystore.p12  # Đường dẫn đến keystore
    key-store-password: 123456  # Mật khẩu đã đặt khi tạo keystore
    key-store-type: PKCS12
    key-alias: tomcat  # Alias khi export file keystore

  
  servlet:
    context-path: /api/v1
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
  datasource:
    url:  ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/pis}
    username: ${SPRING_DATASOURCE_USERNAME:SA}
    password: ${SPRING_DATASOURCE_PASSWORD:Password789}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none  # create, update, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: kendyle2702@gmail.com
    password: ogvf fphi uyzc wbyy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
azure:
  storage:
    connection-string: "DefaultEndpointsProtocol=https;AccountName=pisnewcontainer;AccountKey=gBlvX0fMIRhySg3Xy1u8vT3BCVV7lD/HRcuxhnWM3dyuYEAlilU1Dr8mZAgV7dW7EluN2Bz4mW+G+AStld/IXA==;EndpointSuffix=core.windows.net"
    container-name: "image"



jwt:
  signerKey: "YqvUBDFkYwvZFFKHHRoePHueiKAmrVdubXLJQbP04rfshwdSjnI7KDUq/IIQCCVO"



#ogvf fphi uyzc wbyy
