server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=pis;encrypt=true;trustServerCertificate=true
    username: SA
    password: Password789
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none  # create, update, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: kendyle2702@gmail.com
    password: ogvf fphi uyzc wbyy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
            scope:
              - email
              - profile



jwt:
  signerKey: "YqvUBDFkYwvZFFKHHRoePHueiKAmrVdubXLJQbP04rfshwdSjnI7KDUq/IIQCCVO"



#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
#ogvf fphi uyzc wbyy